### PR TITLE
Specialize more `consume_iter`s

### PR DESCRIPTION
**Pull request by huonw**
This specializes the remaining "obvious" `consume_iter`s for the second part of #465. Benchmarks are included in each commit (the first specializes the types that can just defer to a `std` API, the second two require a bit more work); summary (on a 6 core/12 thread machine):

- on the included benchmarks:
  - `find` is up to 1.5x faster (`find::size1::parallel_find_middle`)
  - `collect` is up to 4x faster (`vec_collect::vec_i_filtered::with_collect`)
- using basic program that does something like `(0..std::u32::MAX).into_par_iter().<OPERATION>.map(test::black_box).count()`
  - with no operation (i.e. just testing `map`/`count`): 8x faster
  - with `.map(Some).while_some()`: 3x faster
  - with `.intersperse(1)`: 10x faster

The remaining types without a specialization are:

```
$ rg --files-with-matches 'fn consume' src/iter | xargs rg --files-without-match 'fn consume_iter'
src/iter/filter_map.rs
src/iter/unzip.rs
src/iter/try_fold.rs
src/iter/try_reduce_with.rs
src/iter/try_reduce.rs
src/iter/filter.rs
src/iter/flat_map.rs
src/iter/find_first_last/mod.rs
src/iter/collect/consumer.rs
```

(I've started a WIP branch for the `try_*` types at https://github.com/huonw/rayon/tree/try_fold; diff to this PR: https://github.com/huonw/rayon/compare/iter-opts...try_fold.)

### CODE REVIEW

**Comment by huonw** [comment]
Hi @cuviper and/or @nikomatsakis, I'd love to see this progress, so a review would be appreciated. Thanks!

**Comment by cuviper** [comment]
> 1.5x, 4x, 8x, 3x, 10x

Woah! I expected only modest gains available here, not entire multiples. Thanks for doing this!

I think we need to be a little more careful about checking `full` flags though, for those that may process an arbitrary number of items before anything actually reaches the base consumer. This applies to `filter`, `filter_map`, and `fold`, as well as `find_any` needing to check its global state. In `while_some` you do have a load of its global state, which is good, but it also needs to consult whether its base is full.

For a tangible (though exaggerated) example of this, I tried adding this in tests/octillion.rs:

```rust
#[test]
fn find_any_octillion() {
    let x = octillion().find_any(|&x| x > OCTILLION / 2);
    assert!(x.is_some());
}
```

On the master branch, this takes only a couple milliseconds, even in debug mode, as thread creation itself is the only real work. The higher splits will instantly find a match, short-circuiting the lower splits. (Assuming at least two threads -- if we really add this test, we should guarantee that like some of the other tests in that file do.)

On your branch, the lower splits continue through their entire iterator, without looking up to see that the shared `found` state was set. I think this can be solved using a `take_while`, and similarly in `filter` etc. We'll give up some performance, sadly, but that seems necessary for short-circuiting to work correctly. Hopefully codegen can at least inline and const-prop the cases where `full` is always false.

**Comment by huonw** [comment]
That's a good point! Fixing it for `find` and `fold` should be easy enough, but I can't quite see how to handle it for `filter`/`filter_map`: `self.base` is moved into the `consume_iter` call, and thus there's no way to call its `full` in the iterator adaptor chain. I may have to revert them.

**Comment by cuviper** [comment]
> but I can't quite see how to handle it for `filter`/`filter_map`: `self.base` is moved into the `consume_iter` call, and thus there's no way to call its `full` in the iterator adaptor chain.

That's annoying. You may be able to get by with `take_while().filter().next()`, pulling one item at a time to pass to the consumer. I guess the performance compared to plain `consume` will depend on how many items the `filter` is actually filtering out. If you do revert, please put a comment in there so we remember these considerations.

> I don't think that concern applies to `while_some` because it isn't consuming an arbitrary number of elements for each output,

Ah, yes, you're right. It does need to load its own global flag as you're doing, since the base consumer won't check that, but the base can otherwise take care of itself.

**Comment by cuviper** [comment]
> Should I also open an issue along the lines of "`Folder` API doesn't allow for internal iteration optimisation of `filter`-like adapters", to remember it for a potential (rayon 2?) API change/iteration/improvement?

Sure, although I'm not sure what that change would look like, so if you have ideas please sketch them out. You'd still have the same problem if `consume_iter` took `&mut self`, for instance. Or the folder could have a method to return some associated `type Full` object, but this couldn't reference the folder's own state.

**Comment by huonw** [comment]
I had the same thought about using an associated type, and I think not being able to reference the folder's state is an ok limitation: most things either are never full or need to communicate with other threads to check full-ness anyway. I opened https://github.com/rayon-rs/rayon/issues/632.

**Comment by huonw** [comment]
I added a commit that:

- reverts the change for `filter` and `filter_map`
- adds `take_while` to `fold` and `find_any`
- extends the octillion tests to cover the above

Unsurprisingly, this makes a program like the following slightly slower compared to the direct `consume_iter` without a check, but it's still faster than the non-specialized form.

```rust
#![feature(test)]

extern crate test;
extern crate rayon;
use rayon::prelude::*;

fn main() {
    let count = (0..std::u32::MAX)
        .into_par_iter()
        .map(test::black_box)
        .find_any(|_| test::black_box(false));
    println!("{:?}", count);
}
```

```
$ hyperfine ./find-original ./find-no-check ./find-check
Benchmark #1: ./find-original
  Time (mean ± σ):     627.6 ms ±  25.7 ms    [User: 7.130 s, System: 0.014 s]
  Range (min … max):   588.4 ms … 656.4 ms    10 runs

Benchmark #2: ./find-no-check
  Time (mean ± σ):     481.5 ms ±  10.8 ms    [User: 5.415 s, System: 0.013 s]
  Range (min … max):   468.9 ms … 498.2 ms    10 runs

Benchmark #3: ./find-check
  Time (mean ± σ):     562.3 ms ±  11.8 ms    [User: 6.363 s, System: 0.013 s]
  Range (min … max):   542.5 ms … 578.2 ms    10 runs
```

(find-original = without specialization; find-no-check = custom `consume_iter` without `take_while`; find-check = this commit)

**Comment by huonw** [comment]
Done (formatting isn't checked on CI?).

Let me know if you'd like the commits squashed, for a clean history.

**Comment by cuviper** [comment]
> Done (formatting isn't checked on CI?).

No, we need to figure that out... #612 

> Let me know if you'd like the commits squashed, for a clean history.

This is clean enough for me, and there are important details in your "check full" commit.

bors r+

**Pull request merged**
