### PR TITLE
link to par_sort resolves

### PR DESCRIPTION
**Pull request by AndyGauge**
I found a dead link.

### CODE REVIEW

**Comment by cuviper** [comment]
Ah, this is awkward.  Your fix is correct for the re-export as [`rayon::join`](https://docs.rs/rayon/1.0.1/rayon/fn.join.html#examples), but it will still be a broken link for [`rayon_core::join`](https://docs.rs/rayon-core/1.4.0/rayon_core/fn.join.html#examples).  I'm not sure if there's any good solution for cross-crate links like that.

**Comment by AndyGauge** [comment]
I forgot about rayon_core with the links.  I tested this in both.

**Comment by cuviper** [comment]
It will still be broken when rayon-core is documented on its own, as docs.rs does, but I don't know what to do about that.  Anyway, this is a clear improvement, thanks!

bors r+

**Comment by AndyGauge** [comment]
I didn't look carefully at the link you sent, but now I see what you are talking about.  I don't know how to solve that.

**Pull request merged**
