### PR TITLE
update crossbeam-deque to 0.6

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by debris** [comment]
travis fails, cause `crossbeam-utils` cannot be compiled with `rustc 1.13.0`. Is there any reason to be backwards compatible with 2y old rust?

**Comment by stjepang** [comment]
See #586 for a previous discussion on bumping `crossbeam-utils` :)

**Comment by debris** [comment]
haha, thanks :)

**Comment by cuviper** [comment]
Yeah, it's a matter of policy.  And while I'm sure we will bump it eventually, 1.25 is too recent IMO.

Thanks anyway!

**Pull request closed without merging**
