### PR TITLE
Note how minimum length behaves with combined iterators

### LINKED ISSUE #472: What's the meaning of with_min_len with zip and flat_map?
The documentation of `with_min_len` doesn't explain how multiple values of `with_min_len` interact, e.g.

```rust
vec.par_iter().with_min_len(a)
.zip(vec2.par_iter().with_min_len(b))
.flat_map(|_| {
  other.par_iter().with_min_len(c)
});
```

### PR DESCRIPTION
**Pull request by pornel**
Closes #472

### CODE REVIEW

**Comment by cuviper** [comment]
Looks good!  Can you please add a similar note to `with_max_len`?

**Comment by pornel** [comment]
OK. I assume it's a logical opposite for the max function.

**Comment by cuviper** [comment]
Yep, thanks!

bors r+

**Comment by cuviper** [comment]
Surely not your fault, but on OSX nightly with `rayon_unstable`:

```
---- src/range.rs - range (line 6) stdout ----
	thread 'rustc' panicked at 'test executable failed:

', src/librustdoc/test.rs:323:16
```

But the regular OSX nightly passed, and `range.rs` shouldn't be affected by any `rayon_unstable` stuff, so let's try again...

bors r+

**Pull request merged**
