### PR TITLE
Release Rayon 1.0! (and rayon-core 1.4)

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by cuviper** [comment]
[rendered release notes](https://github.com/cuviper/rayon/blob/rayon-1.0/RELEASES.md#release-rayon-100--rayon-core-140)

The only outstanding milestone issue is #236, but completion on that seems nebulous.  I don't think we really need to block the release on docs anyway.

The last thing I noticed is that `rayon_core::ThreadPoolInitError` is not re-exported in `rayon`.  Should we add that?

**Comment by jwass** [comment]
@cuviper I think the reason `ThreadPoolInitError` wasn't re-exported was that the old `GlobalPoolAlreadyInitialized` was never exported either. (At least that was my thinking at the time). Although maybe it still should be.

**Comment by cuviper** [comment]
Also, those methods are now `build` -- should it be called `ThreadPoolBuildError`?

**Comment by cuviper** [comment]
@jwass fair point, but still worth considering.

**Comment by KodrAus** [comment]
> The only outstanding milestone issue is #236, but completion on that seems nebulous. I don't think we really need to block the release on docs anyway.

I agree, the docs are in pretty nice shape, and some of the tooling work going on in `rustdoc` this year could offer some new dimensions to expand the docs in anyway.

**Comment by nikomatsakis** [comment]
Very exciting!

**Comment by cuviper** [comment]
bors r=nikomatsakis

**Comment by cuviper** [comment]
Published!

**Pull request merged**
