### PR TITLE
Re-wrap the FAQ to 80 character width

### PR DESCRIPTION
**Pull request by atouchet**

### CODE REVIEW

**Comment by cuviper** [comment]
What text width did you use? It looks rather narrow...

**Comment by atouchet** [comment]
Those are 70 character widths which is what the Readme and the rest of the FAQ already appear to be using. This is just adjusting a few paragraphs to be consistent with those.

**Comment by cuviper** [comment]
I think it may have been 72, which would still fit some of the existing lines here. But if we're going to rewrap, I'd prefer to go wider to 80.

**Comment by atouchet** [comment]
I tried taking a look and I don't think the rest of the document matches 72 but regardless I could rewrap it to 80 if you would prefer that.

**Comment by cuviper** [comment]
We haven't enforced anything, so I have no doubt that it's inconsistent. Yes, let's do 80 please.

**Comment by atouchet** [comment]
Okay. Should the Readme be rewrapped too? It is also currently using 70.

**Comment by cuviper** [comment]
Sure, if you're interested, go ahead in the readme too.

**Comment by atouchet** [comment]
There ended up being more docs in this repo than I originally realized so I opted to just re-wrap the FAQ page to 80.

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
