### PR TITLE
Parking lot experiment

### PR DESCRIPTION
**Pull request by JackThomson2**
I've had a play switching the mutex & condvars implementations from std to Parking lot. In my use case seem to show a regression in perf but I thought I'd share to see if it helps anyone else.

Thanks Jack

### CODE REVIEW

**Comment by cuviper** [comment]
Can you share your measured perf results?

**Comment by JackThomson2** [comment]
Sure, pretty busy at the moment, I'll ping you when I get a chance to run it again.

**Comment by JackThomson2** [comment]
Hi sorry for the long delay here are the benchmark results on my machine.

<details>

<summary>Benchmark Results</summary>

# Game Of Life

- PARKING LOT: 
    serial:  109924328 ns
    parallel:   52439514 ns -> 2.10x speedup
    par_bridge:  365073776 ns -> 0.30x speedup

- MASTER:   
    serial:  111545061 ns
    parallel:   54061473 ns -> 2.06x speedup
    par_bridge:  362224338 ns -> 0.31x speedup

# NBODY

- PARKING LOT: 
    Parallel time    : 1689592241 ns
    ParReduce time   : 5437488179 ns
    Sequential time  : 3666408180 ns
    Parallel speedup : 2.169996
    ParReduce speedup: 0.67428344

- MASTER:   
    Parallel time    : 1686918441 ns
    ParReduce time   : 5368962136 ns
    Sequential time  : 3611151497 ns
    Parallel speedup : 2.1406796
    ParReduce speedup: 0.6725977


# SIEVE

- PARKING LOT: 
    serial: 4478577710 ns
    chunks: 1096277249 ns -> 4.09x speedup
    parallel:  553369806 ns -> 1.98x speedup

- MASTER:   
    serial: 4501561130 ns
    chunks: 1045074189 ns -> 4.31x speedup
    parallel:  559258863 ns -> 1.87x speedup


# MATMUL

- PARKING LOT: 
    seq row-major:  1024x1024 matrix: 6.4572415 s
    seq z-order:    1024x1024 matrix: 1.2970779 s
    par z-order:    1024x1024 matrix: 0.5232101 s
    par strassen:   1024x1024 matrix: 0.2627471 s
    speedup: 2.48x

- MASTER:   
    seq row-major:  1024x1024 matrix: 8.5225115 s
    seq z-order:    1024x1024 matrix: 1.2332067 s
    par z-order:    1024x1024 matrix: 0.46749043 s
    par strassen:   1024x1024 matrix: 0.26851904 s
    speedup: 2.64x


# MERGESORT

- PARKING LOT: 
    seq: sorted 250000000 ints: 20.928692 s
    par: sorted 250000000 ints: 7.131621 s
    speedup: 2.93x

- MASTER:   
    seq: sorted 250000000 ints: 21.051676 s
    par: sorted 250000000 ints: 7.458955 s
    speedup: 2.82x

# QUICKSORT

- PARKING LOT: 
    seq: sorted 250000000 ints: 25.034409 s
    par: sorted 250000000 ints: 10.026911 s
    speedup: 2.50x

- MASTER:   
    seq: sorted 250000000 ints: 24.510712 s
    par: sorted 250000000 ints: 9.804245 s
    speedup: 2.50x

</details>

**Comment by cuviper** [comment]
What's your host CPU and OS? This comparison will also depend on how good the system primitives are to begin with.

The changes in sequential results also seems to indicate that a lot of this is noise, or perhaps influenced by perturbations to optimization, like how codegen-units are split.

**Comment by JackThomson2** [comment]
> What's your host CPU and OS? This comparison will also depend on how good the system primitives are to begin with.
> 
> The changes in sequential results also seems to indicate that a lot of this is noise, or perhaps influenced by perturbations to optimization, like how codegen-units are split.

I'm running this on OSX 11.0.1 with a dual core i7-7660U.

I had wondered about the codegen units, want me to run with codegen units set to 1?

**Comment by cuviper** [comment]
You're welcome to experiment, but my takeaway is simply that it's not a clear win. If parking-lot is lost in the noise of stuff like codegen-units and LTO, then I think it's not worth worrying about for rayon.

If we had some killer workload where parking-lot helped a lot, and it was good/neutral elsewhere, it would be more compelling.

**Comment by JackThomson2** [comment]
My thoughts exactly, I'll close the PR for now. I'll have a play and see if I can figure anything out. 

Cheers Jack

**Pull request closed without merging**
