### PR TITLE
Automatically check if README.md examples are working when running "cargo test"

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Since rustdoc nightly now provides "cfg(test)" when running on test mode, we can now use this macro on test mode only to check if README.md examples are working as expected.

### CODE REVIEW

**Comment by cuviper** [comment]
How do I know if this worked? I don't see README tests in the log:
https://travis-ci.org/rayon-rs/rayon/jobs/525713032

**Comment by GuillaumeGomez** [comment]
It only work on nightly for the moment. The PR got merged recently: https://github.com/rust-lang/rust/pull/59940, so in 6 weeks it'll be in stable.

I can add tests for nightly on your CI if you want alongside the others?

**Comment by cuviper** [comment]
Ah, we do have CI for nightly, but only on the full bors check. Let's just go for it:

bors r+

**Comment by GuillaumeGomez** [comment]
Can you tell me what failed please? :)

**Comment by cuviper** [comment]
Looks like a UI issue in rayon-core, unrelated to your change:

```text
---- src/compile_fail/scope_join_bad.rs - compile_fail::scope_join_bad (line 1) stdout ----
error[E0373]: closure may outlive the current function, but it borrows `x`, which is owned by the current function
 --> src/compile_fail/scope_join_bad.rs:8:17
  |
7 |     rayon_core::scope(|s| {
  |                        - has type `&rayon_core::Scope<'1>`
8 |         let x = 22;
9 |         s.spawn(|_| f(&x)); //~ ERROR `x` does not live long enough
  |                 ^^^    - `x` is borrowed here
  |                 |
  |                 may outlive borrowed value `x`
  |
note: function requires argument type to outlive `'1`
 --> src/compile_fail/scope_join_bad.rs:8:9
  |
9 |         s.spawn(|_| f(&x)); //~ ERROR `x` does not live long enough
  |         ^^^^^^^^^^^^^^^^^^
help: to force the closure to take ownership of `x` (and any other referenced variables), use the `move` keyword
  |
9 |         s.spawn(move |_| f(&x)); //~ ERROR `x` does not live long enough
  |                 ^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0373`.
thread 'src/compile_fail/scope_join_bad.rs - compile_fail::scope_join_bad (line 1)' panicked at 'Some expected error codes were not found: ["E0597"]', src/librustdoc/test.rs:315:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by GuillaumeGomez** [comment]
Oh? That's surprising. Well, I'll let you handle this part then. Thanks for showing me the error! :)

**Comment by cuviper** [comment]
I believe the error change is from NLL being enabled for 2015 edition. Fortunately, `compile_fail` doc tests still only check the error string on nightly, so we don't have to worry about matching older errors.

bors r+

**Comment by cuviper** [comment]
Bah, more error changes in rayon-futures...

**Comment by GuillaumeGomez** [comment]
Congrats and thanks for fixing!

**Pull request merged**
