### PR TITLE
impl FromParallelIterator for tuple pairs

### PR DESCRIPTION
**Pull request by cuviper**
Like #604 for `ParallelExtend`, implementing `FromParallelIterator` for tuple pairs opens up new possibilities for nesting `collect`. The possibility of short-circuiting into `Result<(T, U), E>` for #801 is particularly motivating.

- `FromParallelIterator<(A, B)> for (FromA, FromB)` works like `unzip`
- `FromParallelIterator<Either<L, R>> for (A, B)` works like `partition_map`

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@cuviper 

> The possibility of short-circuiting into Result<(T, U), E> for #801 is particularly motivating.

Can you explain this a bit more? Is that potential future work or did I miss something.

**Comment by cuviper** [comment]
It's a composition. `Result<X, E>` implements a short-circuiting `FromParallelIterator` for any `X: FromParallelIterator`. With this PR, that `X` can be `(T, U)`, so we now have a short-circuiting `unzip`/`partition_map` via `collect::<Result<(T, U), E>>()`.

**Comment by nikomatsakis** [comment]
I see.

**Comment by cuviper** [comment]
I finally got around to adding doc-examples for this.

**Comment by nikomatsakis** [comment]
I think this will not get accepted in the stdlib, right?

**Comment by cuviper** [comment]
> I think this will not get accepted in the stdlib, right?

I expect not, but I haven't even proposed it yet. I think given how `IntoIterator` rust-lang/rust#78204 went, it's unlikely that `FromIterator` would be accepted. But I also think it's unlikely that `FromIterator` for tuples would ever be added with _different_ semantics, so I'm not worried about us being incompatible.

And I do think it's still justified here, because it's otherwise really hard to collect multiple things in parallel. With serial `Iterator`, it's trivial to just write a manual `for` loop that unpacks items and stuffs them into however many collections you want. With `ParallelIterator`, collection is much more complicated to do manually, probably best as `fold`+`reduce`, or `try_fold`+`try_reduce` if you want short-circuiting. Yet this PR is a relatively small addition that enables a lot of power easily.

**Comment by nikomatsakis** [comment]
That makes sense.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
I'd be r+ on landing this.

**Comment by cuviper** [comment]
bors r=nikomatsakis

**Pull request merged**
