### PR TITLE
use clone_from in quicksort bench

### PR DESCRIPTION
**Pull request by TheIronBorn**

### CODE REVIEW

**Comment by cuviper** [comment]
Sounds good -- can you do the same in the merge-sort bench?

**Comment by TheIronBorn** [comment]
Done, also allocated before timing starts

**Comment by cuviper** [comment]
Thanks!

**Comment by TheIronBorn** [comment]
I suppose the first iteration might elide the memcpy. If anyone can suggest a way to avoid that please do.

**Comment by cuviper** [comment]
I doubt it will do that, but we could replace that outer clone with just `Vec::with_capacity`.

**Pull request merged**
